BEGIN;

CREATE TABLE IF NOT EXISTS public.user_experience_ratings (
  rating_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  reservation_id bigint NOT NULL UNIQUE
    REFERENCES public.reservations(reservation_id) ON DELETE CASCADE,
  rating smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS reservations_user_created_order_idx
  ON public.reservations (user_id, created_at, reservation_id);

ALTER TABLE public.user_experience_ratings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.user_experience_ratings
  FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.user_experience_ratings TO service_role;

CREATE OR REPLACE FUNCTION public.should_prompt_experience_rating(
  p_reservation_id bigint
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, private, auth
AS $$
DECLARE
  profile_id bigint;
  target_created_at timestamptz;
  request_number bigint;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication is required to check rating eligibility.'
      USING ERRCODE = '42501';
  END IF;

  profile_id := private.current_profile_id();
  IF profile_id IS NULL THEN
    RAISE EXCEPTION 'The authenticated profile could not be found.'
      USING ERRCODE = '42501';
  END IF;

  SELECT reservation.created_at
  INTO target_created_at
  FROM public.reservations AS reservation
  WHERE reservation.reservation_id = p_reservation_id
    AND reservation.user_id = profile_id
    AND EXISTS (
      SELECT 1
      FROM public.reservation_details AS detail
      WHERE detail.reservation_id = reservation.reservation_id
    );

  IF target_created_at IS NULL THEN
    RAISE EXCEPTION 'The reservation does not belong to the authenticated profile.'
      USING ERRCODE = '42501';
  END IF;

  SELECT count(*)
  INTO request_number
  FROM public.reservations AS reservation
  WHERE reservation.user_id = profile_id
    AND (reservation.created_at, reservation.reservation_id)
      <= (target_created_at, p_reservation_id)
    AND EXISTS (
      SELECT 1
      FROM public.reservation_details AS detail
      WHERE detail.reservation_id = reservation.reservation_id
    );

  RETURN (request_number = 1 OR (request_number > 1 AND (request_number - 1) % 10 = 0))
    AND NOT EXISTS (
      SELECT 1
      FROM public.user_experience_ratings AS rating
      WHERE rating.reservation_id = p_reservation_id
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.submit_experience_rating(
  p_reservation_id bigint,
  p_rating smallint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, private, auth
AS $$
DECLARE
  profile_id bigint;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication is required to submit a rating.'
      USING ERRCODE = '42501';
  END IF;

  IF p_rating IS NULL OR p_rating < 1 OR p_rating > 5 THEN
    RAISE EXCEPTION 'Rating must be between 1 and 5.'
      USING ERRCODE = '22023';
  END IF;

  profile_id := private.current_profile_id();
  IF profile_id IS NULL
     OR NOT public.should_prompt_experience_rating(p_reservation_id) THEN
    RAISE EXCEPTION 'This reservation is not eligible for a rating.'
      USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.user_experience_ratings (user_id, reservation_id, rating)
  VALUES (profile_id, p_reservation_id, p_rating);
END;
$$;

REVOKE ALL ON FUNCTION public.should_prompt_experience_rating(bigint)
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.submit_experience_rating(bigint, smallint)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.should_prompt_experience_rating(bigint)
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_experience_rating(bigint, smallint)
  TO authenticated;

COMMIT;
