BEGIN;

CREATE TABLE IF NOT EXISTS public.user_feedback (
  feedback_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  navigation_satisfaction smallint NOT NULL
    CHECK (navigation_satisfaction BETWEEN 1 AND 4),
  reservation_satisfaction smallint NOT NULL
    CHECK (reservation_satisfaction BETWEEN 1 AND 4),
  responsiveness_satisfaction smallint NOT NULL
    CHECK (responsiveness_satisfaction BETWEEN 1 AND 4),
  information_satisfaction smallint NOT NULL
    CHECK (information_satisfaction BETWEEN 1 AND 4),
  additional_comments text
    CHECK (additional_comments IS NULL OR char_length(additional_comments) <= 2000),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS user_feedback_user_created_idx
  ON public.user_feedback (user_id, created_at DESC);

ALTER TABLE public.user_feedback ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.user_feedback
  FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.user_feedback TO service_role;

CREATE OR REPLACE FUNCTION public.submit_user_feedback(
  p_navigation_satisfaction smallint,
  p_reservation_satisfaction smallint,
  p_responsiveness_satisfaction smallint,
  p_information_satisfaction smallint,
  p_additional_comments text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, private, auth
AS $$
DECLARE
  profile_id bigint;
  created_feedback_id bigint;
  normalized_comments text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication is required to submit feedback.'
      USING ERRCODE = '42501';
  END IF;

  profile_id := private.current_profile_id();
  IF profile_id IS NULL THEN
    RAISE EXCEPTION 'The authenticated profile could not be found.'
      USING ERRCODE = '42501';
  END IF;

  IF p_navigation_satisfaction IS NULL
     OR p_navigation_satisfaction NOT BETWEEN 1 AND 4
     OR p_reservation_satisfaction IS NULL
     OR p_reservation_satisfaction NOT BETWEEN 1 AND 4
     OR p_responsiveness_satisfaction IS NULL
     OR p_responsiveness_satisfaction NOT BETWEEN 1 AND 4
     OR p_information_satisfaction IS NULL
     OR p_information_satisfaction NOT BETWEEN 1 AND 4 THEN
    RAISE EXCEPTION 'Each survey answer must be between 1 and 4.'
      USING ERRCODE = '22023';
  END IF;

  normalized_comments := NULLIF(btrim(p_additional_comments), '');
  IF normalized_comments IS NOT NULL
     AND char_length(normalized_comments) > 2000 THEN
    RAISE EXCEPTION 'Additional comments cannot exceed 2000 characters.'
      USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.user_feedback (
    user_id,
    navigation_satisfaction,
    reservation_satisfaction,
    responsiveness_satisfaction,
    information_satisfaction,
    additional_comments
  )
  VALUES (
    profile_id,
    p_navigation_satisfaction,
    p_reservation_satisfaction,
    p_responsiveness_satisfaction,
    p_information_satisfaction,
    normalized_comments
  )
  RETURNING feedback_id INTO created_feedback_id;

  RETURN created_feedback_id;
END;
$$;

REVOKE ALL ON FUNCTION public.submit_user_feedback(smallint, smallint, smallint, smallint, text)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.submit_user_feedback(smallint, smallint, smallint, smallint, text)
  TO authenticated;

COMMIT;
